name: Data Mining 2019
markdown: kramdown
baseurl: "/Data-mining"
permalink: /blog/:year/:month/:day/:title/

theme: jekyll-theme-minimal
title: Data Mining
description: This is a blog to introduce basic concepts of Data Mining
logo: /images/NOOBS_Logo.png
show_downloads: false
